### ISSUE TITLE
Error : IndexError: list index out of range

### ISSUE THREAD

**Issue by Lolojr** [pySRURGS/pySRURGS#15]
Hello, 

I used pySRURGS to search for the equation of best fit for my numerical dataset and everything was going great until, just after "Running in multi processor mode" finished (100%), it doesn't display the equations with R^2, but Traceback the following error : 

Traceback (most recent call last):
  File "pySRURGS.py", line 2714, in <module>
    plot_results(SRconfig)
  File "pySRURGS.py", line 2204, in plot_results
    best_model = result_list._results[0]
IndexError: list index out of range

How may I fix this problem?

Please find attached all the optionnal arguments that I considered.
<img width="952" alt="Screenshot 2020-05-01 at 01 04 54" src="https://user-images.githubusercontent.com/18407439/80767252-cc046380-8b47-11ea-88ea-d8a35c4f4b11.png">
Regards,

Loïc

**Comment by sohrabtowfighi** [comment]
The error is saying that your result list is empty. 
Try not using the backslash in the path to your data file. Try using, in double quotes, `"/Users/Lverbeke/Desktop/PROJET MA1/data_test.csv"`.
Does running `python3 test.py` pass all the tests?

**Comment by sohrabtowfighi** [comment]
Can you let me know a bit more about your configuration? Are you using python3.6/3.7? Does your CSV have a header row?

**Comment by Lolojr** [comment]
Thanks for your response!
I am using python 3.8 and I have a header in my CSV file (contains 4 features, 720 samples, and the target at the rightmost column). 
When running `python3 test.py` (after installing pbs module) it passes all the 18 tests and display : `"Sh.py is the new pbs.  Please download and install sh.py"` . 
I ran the Symbolic regression algorithm (without backslash in my cvs file path) but it still give me the same error message..

**Comment by pySRURGS** [comment]
What are your variable names in the header?
Did you install the prerequisites using the requirements.txt file?

**Comment by pySRURGS** [comment]
From what I gather this issue has more to do with the specifics of your setup than the code itself, since the test suite works fine according to your previous reply. Also, the software was not designed for python3.8 and so if the issue happens to be due to your use of python3.8 I will not know.

**Comment by Lolojr** [comment]
My variable names are : X0, X1, X2, X3 and y (so I did not use special characters or spaces in variable names). I followed all your instructions when getting started and installed all requirements. So, I will try with python 3.6/3.7. But anyway, thanks a lot for your time! I will let you know when I find what my issue was. 

Regards,

Loïc

**Comment by pySRURGS** [comment]
You said you needed to install the pbs module. That is only necessary for windows as far as I know and both sh and PBS would have been installed when you installed from the requirements.txt file. Moreover, PBS is only used when the import of sh fails, so I think you may not have sh installed.

**Comment by Lolojr** [comment]
I started over from the beginning with python3.7 and when I ran `python3.7 test.py` and (after running the 18 tests) it returned me: `FAILED (errors=8) ` with the same message error for all errors which is : `ValueError: unsupported pickle protocol: 5`. Do you know how may I deal with that ? 
<img width="622" alt="Screenshot 2020-05-01 at 03 31 01" src="https://user-images.githubusercontent.com/18407439/80774068-358e6d00-8b5c-11ea-84c0-ace0796c90fa.png">

**Comment by sohrabtowfighi** [comment]
I can put a patch for this. You need to manually delete the database file
in the 'db' directory.

**Comment by pySRURGS** [comment]
If your python3.7 install is not the default python3 found in terminal, that might also be the cause of issue with the test.py script.

**Comment by sohrabtowfighi** [comment]
I previously said I can make a patch for this but upon further review I think the code is fine and your issue likely has to do with your terminal environment's python3 not being the same python3 that you used to run test.py. Either way, this is outside the scope of support that I offer through github issues.

**Comment by pySRURGS** [comment]
This was a bug i failed to identify when editing the multiprocessing functionality. I have since just removed multiprocessing because I think it is not useful in most use-cases. If it is desperately needed, users can look at the JOSS release.
