### ISSUE TITLE
Understanding the random_equation_binary_tree method

### ISSUE THREAD

**Issue by BisUndefined** [pySRURGS/pySRURGS#18]
Hello,
I have juste discover this library and I'm intersting in the random_equation_binary_tree method. I would like to understand how it works but I can't understand the purposes of each parameters and how the nodes are created.
Can someone enlighten me ?

**Comment by pySRURGS** [comment]
It is on arxiv as well.

**Comment by TristanESEO** [comment]
> 

I'm currently reading the paper on SN Applied Science. But in order to be more precise. I am in search of a function that creates mathematical expressions using a binary tree. I already have created my own but I'm not enough satisfied with it and it's a real important step in my project because I'm using it to create my chromosomes for a genetic algorithm project.
That's the reason why I'm asking if I can use your function in the way I described it.

**Comment by pySRURGS** [comment]
Yes.

**Comment by TristanESEO** [comment]
> 

But I can't understand how I can do it as the parameters in the random_equation_binaree_tree_method seems a little disturbing for me. If you have time for me, we can discuss about it through mail or teams conversation. I would be very pleased.

**Comment by pySRURGS** [comment]
User specifies maximum complexity of binary tree. That's it.

**Comment by TristanESEO** [comment]
> User specifies maximum complexity of binary tree. That's it.

But when I try to generate an equation with only one argument completed, it returns me the following error :
equation = pySRURGS.random_equation_binary_tree(2)
TypeError: random_equation_binary_tree() missing 3 required positional arguments: 'cum_weights', 'enumerator', and 'SRconfig'

I might have made a mistake in the way I'm supposed to call this function.

**Comment by pySRURGS** [comment]
Yes. You should look to see how I call the function. Then copy that. The parameters are determined in a way that allows for random search. You need to review what the script does with the user specified maximum complexity and not examine this method in isolation.

**Comment by TristanESEO** [comment]
> Yes. You should look to see how I call the function. Then copy that. The parameters are determined in a way that allows for random search. You need to review what the script does with the user specified maximum complexity and not examine this method in isolation.

Ok, I understand but in which document can I see an exemple ?

**Comment by pySRURGS** [comment]
You need to read the code. It is clearly written. If you cannot you must find someone who can. I cannot support you without payment for time.

**Comment by TristanESEO** [comment]
Thank you for your instructions. Have a great day.

**Comment by pySRURGS** [comment]
Lastly, i should add that once you get an equation from the code, it will be a string. It will not be a data structure. Your program will need to be able to convert the string expression to whatever data structure it uses. Deap has this functionality, I believe.

**Comment by TristanESEO** [comment]
> Lastly, i should add that once you get an equation from the code, it will be a string. It will not be a data structure. Your program will need to be able to convert the string expression to whatever data structure it uses. Deap has this functionality, I believe.

I use the sympy library in my code and the sympify function work on string so it's fine. Thanks again.
