### ISSUE TITLE
Plotting issue

### ISSUE THREAD

**Issue by TristanESEO** [pySRURGS/pySRURGS#19]
Hello,
I'm trying to use the exemple on the READme file but at the end, the plotting crash.
Here is the command I entered (Linux terminal):
~/Desktop/Pysrugs/pySRURGS-master$ python3 pySRURGS.py -max_num_fit_params 3 -max_permitted_trees 1000 -plotting ./csv/x1_squared_minus_five_x3.csv 2000

And here is the error : 
Traceback (most recent call last):
  File "pySRURGS.py", line 2713, in <module>
    plot_results(SRconfig)
  File "pySRURGS.py", line 2203, in plot_results
    best_model = result_list._results[0]
IndexError: list index out of range

Do you know why this error occurs ?

**Comment by pySRURGS** [comment]
This is indeed a bug in the multiprocessing mode. 
You can get around this using the `-single` flag, but I will need to fix this.

**Comment by pySRURGS** [comment]
alternatively you can use the JOSS release which should work - i think i broke the multiprocessing at some point and did not realize

**Comment by BisUndefined** [comment]
> alternatively you can use the JOSS release which should work - i think i broke the multiprocessing at some point and did not realize

Ok, thank you for your response !
