### ISSUE TITLE
arity_one_function

### ISSUE THREAD

**Issue by BisUndefined** [pySRURGS/pySRURGS#21]
I'm trying to define the functions of arity one that are permitted in the symbolic regression run.
So I created a SRconfig object like this :
`SR_config = SymbolicRegressionConfig(r'.\csv\mydataReal.csv', 
                                          None,
                                          n_functions=['add', 'sub', 'mul', 
                                                       'div', 'pow'], 
                                          f_functions=['sin', 'sinh', 'log', 'cos', 'cosh', 'tan', 'tanh', 'exp', 'pow', 'sqrt'], 
                                          max_num_fit_params=2, 
                                          max_permitted_trees=200)`

I just wanted to see a random equation generated so I wrote the following lines :
`(f, n, m, cum_weights, N, dataset, enumerator, _, _) = setup(SR_config)
eqn_str = random_equation_binary_tree(N, cum_weights, enumerator, SR_config)
simple_eqn = simplify_equation_string(eqn_str, dataset)
print(simple_eqn)`

But in my terminal, the following expression was return : (-p1 + x0 + x1 - x3)**(p1 - x0 + x1**2)*(p1**x5 - x1 + x2 + 2*x4)

It seems that it doesn't create an expression with the possible function of arity one I have inserted. Maybe I'm doing something wrong here.

**Comment by pySRURGS** [comment]
The code does not guarantee function of arity one is always included. Run it multiple times and see if any of them have a func of arity one.

**Comment by pySRURGS** [comment]
Actually, you have `**` in your expression, which is the same as `exp`, therefore you do have a func of arity one.

**Comment by BisUndefined** [comment]
I ran my test multiple time but it never shows any expressions with 'sin', 'log' or 'cos' or ...
Can you indicates that the expression must contains one or more function of arity one ?

**Comment by pySRURGS** [comment]
If the proposed function does not evaluate to a real number, or the error is infinite, the proposed model is rejected. You should read the code and edit it to do what you want.

    while valid == False:
        if f == 0:
            eqn_str = random_equation_full_binary_tree(N, cum_weights, 
                                                       enumerator, SRconfig)
        else:
            eqn_str = random_equation_binary_tree(N, cum_weights, enumerator, 
                                                  SRconfig)
        try:
            simple_eqn = simplify_equation_string(eqn_str, dataset)
            path_to_db = SRconfig._path_to_db
            initialize_db(path_to_db)
            params = create_fitting_parameters(dataset._int_max_params)
            (sum_of_squared_residuals, sum_of_squared_totals,
             R2, params_fitted,
             residual) = check_goodness_of_fit(eqn_str, params, SRconfig)
            if np.isnan(R2) or np.isnan(sum_of_squared_totals):
                raise FloatingPointError
            valid = True
        except FloatingPointError:
            pass
