### ISSUE TITLE
JOSS review comments 

### ISSUE THREAD

**Issue by SirSharpest** [pySRURGS/pySRURGS#6]
# Review performed using most-current github (not in releases)
- https://github.com/pySRURGS/pySRURGS.git

# Installation
- Installation instructions work well
  - Though, it maybe worth while putting on pip as a package?

# Testing
- the function `test_command_line_code` shows that tests are done to command-line interface, however this doesn't give an indication to the results of the tests.
  - In other words: a test could be run, instantly return 0 and be considered a "success".
- I wonder, would it be possible to provide a testing table with expected outputs. This way a user can verify that their usage is running as expected

# Documentation
- The URL for documentation https://pysrurgs.github.io/pySRURGS/ doesn't come across as very intuitive, perhaps usage of a documentation generator e.g. Sphinx would do well.
- More clarity could be given in the explanation of results (see below confusion of mine). 

# Methods 
- I haven't dug into the methods too heavily but is it possible to ensure somehow that for given input you always get the same output, the stochasticity of the outputs? I noticed this when my results of your readme.md example were different.

# Results
- How should one interpret the output
    - is `(-p0*p1 + p2 + x**2/p0)**(-x*(p1**p1)**x)` equivalent to ![this](http://www.sciweavers.org/upload/Tex2Img_1567690636/eqn.png) 
      - The pX is the coefficients given as parameters?
- If the above point is understood correct, then it results are not given in their most simplified form (though, I admit this may be a technical misunderstanding of mine)
      
# Other
- As changes were made recently, the releases of the software is now out of date (at time of posting this comment)
- Perhaps I've overlooked it, but was this work funded or supported by any research councils that need mentioned? 
- The acknowledgements cited in the readme.md should be done better
     - You should indicate the artists for the icon, as well as the original location that you took it from, as well as any license which is applied to it
     - The algorithm of Tychonievich, 2013, seems to be a novel addition to your software, did they have enough input in this project to warrent authorship also?

**Comment by SirSharpest** [comment]
This is referencing [JOSS submission](https://github.com/openjournals/joss-reviews/issues/1675)

**Comment by sohrabtowfighi** [comment]
> would it be possible to provide a testing table with expected outputs

I will work on the command line tests using this idea

> The URL for documentation https://pysrurgs.github.io/pySRURGS/ doesn't come across as very intuitive, perhaps usage of a documentation generator e.g. Sphinx would do well.

I am using pydoc, a documentation generator that is part of the python standard library. It may not be as aesthetically pleasing, but it does the job. If you highlight areas where you think documentation deficient I can amend.

> is it possible to ensure somehow that for given input you always get the same output

I can look into the use of random.seed for this purpose 

> is (-p0*p1 + p2 + x**2/p0)**(-x*(p1**p1)**x) equivalent to this LINK

The link is broken. There is no way to guarantee absolute simplification. As per the Sympy documentation, simplification is not clearly defined. They use heuristic methods that may change in the future and we view this as good enough.

> As changes were made recently, the releases of the software is now out of date 

I can make a release and set the version to 0.1. I develop the software live, and I respond to feedback to fix issues as they arrive through the review, so I do not see continued development as a problem. The core functionality has been in place throughout.

> was this work funded or supported by any research councils that need mentioned

This work was not funded 

> You should indicate the artists for the icon, as well as the original location that you took it from, as well as any license which is applied to it

I will try but there was limited information when I looked into this previously. I also dont want to put up the entire volunteer team who worked on the Gnome icon project.

> The algorithm of Tychonievich, 2013, seems to be a novel addition to your software, did they have enough input in this project to warrent authorship also

Dr. Tychonievich was not involved in the formation or development of this work so they are not an author. They have been cited in our paper.

**Comment by pySRURGS** [comment]
I have added the `-deterministic` flag which runs the code in a reproducible way.
The command line tests now check that there is the results table printed.
I added a note to the readme.md for the source where I got the icon and the license is GPL v 2.0 as per the linked wikimedia article.
I will make this version release 0.1.

Closing this issue unless there are issues.
