### ISSUE TITLE
Max. number of fit params

### ISSUE THREAD

**Issue by anthonyrollett** [pySRURGS/pySRURGS#9]
I just tried using SRURG for the first time tonight and it's impressively easy to install and use. This is probably a stupid question but I tried varying Max_num_fit_params (between 1 & 3) but it seemed as I got back the same answer with 3 params (p0, p1, p2), regardless of that input. When I increased to 4 then I saw an additional p3 in the Eq sets.  I apologize if I've misunderstood the method. Thanks, Tony Rollett
PS. I tried editing the pySRURGS.py to have max_num_fit_params=2 but that did not seem to make any difference.

**Comment by pySRURGS** [comment]
I will take a look today and get back to you.

**Comment by pySRURGS** [comment]
I think I figured out what happened. Make sure to specify `-path_to_db` so that your results get saved to different database files. If you do not specify path to database, then pySRURGS saves to the same database file which will be located at the path `./db/${name_of_csv}.db` . If your new results are no better than the old results in the database, pySRURGS will print out the best results from the previous runs. The summary printout only prints the top 5 models in the database. 

It might be that the models with 3 parameters were better than the models with 2 parameters, and so only models with 3 parameters were printed.

Let me know if you need further assistance.

**Comment by anthonyrollett** [comment]
Thank you!!!

> baldy:pySRURGS rollett$ python3 pySRURGS.py -path_to_db ../NASA_Bingo/CangZ-keyhole_porosity-Apr20/pySRURGS/1param/db -max_num_fit_params 1 -max_permitted_trees 1000 -plotting ../NASA_Bingo/CangZ-keyhole_porosity-Apr20/FullyMelt-KeyholePorosity-Depth-Powder_Pores-2columns.csv 1000
> Running in multi processor mode
> 1024it [01:42,  9.94it/s]                                                                                                                          
> Making sure we meet the iters value
>   Normalized Mean Squared Error       R^2  Equation, simplified                                                    Parameters
> -------------------------------  --------  --------------------------------------------------------------------  ------------
>                         1081.1   0.7453    ((p0**2*x + (p0**p0)**p0)/(p0*x))**(x**(-p0)*(p0**2 - x)/p0)                 0.648
>                         1085.78  0.755879  (2*p0**5 - x**2 + x**p0)/p0**3                                               2
>                         1092.99  0.767964  p0**(-p0 - 2)*x**(p0 - 2)*(p0 - 1)                                           4.19
>                         1093.01  0.765378  -p0**2 + p0 - x**2 + (x**2)**p0                                              1
>                         1093.31  0.768453  (p0*(p0 - x**2 + (p0 + 2*x)**(p0/x)) - (p0 - x)*(p0**p0 + x**p0))/p0         1
> The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.
> The PostScript backend does not support transparency; partially transparent artists will be rendered opaque.



Above is what I got. For plotting the results, one has to have an “image” directory so that the script can store the plots there and then “mv” the “image” folder so that one can save the plots before trying another fit.

Anyway, I’m impressed and will recommend it to my students and colleagues. I took a look at gplearn, e.g., but was very confused by the expectation that one would always be fitting z against (x,y). Colleagues of mine at NASA wrote NASA-bingo (also on GitHub) but it’s distinctly harder to install and use.

Running (mostly) on macOS 10.14, BTW

thanks again,
Tony Rollett

**Comment by pySRURGS** [comment]
I'm very glad that it was useful to you. 

If you end up publishing work with it, I would very much appreciate a citation of https://doi.org/10.1007/s42452-019-1734-3

I am here to support you and your colleagues should they wish to learn about and use the software.

Kind regards, 
Sohrab

**Comment by anthonyrollett** [comment]
I will certainly cite the paper if we publish with it.
One more question: is it possible to use a column of weights? I don’t have many data points so the results vary a lot (as expected): being able to use a set of weighting factors would be useful.
thanks again
Tony

**Comment by pySRURGS** [comment]
After reviewing the code it does not seem like too much work to incorporate this weighting factor suggestion so I will create a new issue for it and implement.
